<form id="<?=$this->formName?>" class="form-horizontal" name="<?=$this->formName?>" method="post" action ="<?=$this->formAction?>">
    <fieldset>

        <?=$this->wizardFormCurrentStep?>
        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="Address">Address</label>
            <div class="col-md-4">
                <input id="address" name="address" placeholder="Address" class="form-control input-md" type="text"value="<?=$this->address?>">
            </div>
        </div>


    </fieldset>
</form>