<div id="fb-root"></div>
<script>
    window.fbAsyncInit = function() {
        FB.init({
            appId      : '448971508600364',
            xfbml      : true,
            version    : 'v2.2'
        });
    };

    (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

<div class="jumbotron">
    <div class="container">

        <img src="/img/largelogo.png" alt="lib-logo"/>


        <p class="lead">
            <?php echo sprintf($this->translate('A powerful ajax module for the Zend Framework 2'),
                '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">',
                '</a>',
                '<a href="http://www.zend.com/" target="_blank">',
                '</a>',
                '<a href="http://www.wasabilib.org" target="_blank">', '</a>') ?>

        </p>

        <p class="lead">
            <a class="btn btn-info"
               href="/application/pages/gettingStarted">  <i class="fa fa-play"></i> <?php echo $this->translate('Getting Started') ?></a>
            <a class="btn btn-info" href="https://github.com/wasabilib"
               target="_blank"><i class="fa fa-download"></i> <?php echo $this->translate('Download on GitHub') ?></a>
        </p>
    </div>
</div>

    <div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body same-height">
                <p><?php echo sprintf($this->translate('WasabiLib for Zend Framework 2 is under active development. Follow the %sWiki%s on Github for news.'),'<a href="https://github.com/wasabilib/wasabilib/wiki">','</a>'); ?>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover WasabiLib') ?></h3>
            </div>
            <div class="panel-body same-height">
                <p><?php echo sprintf($this->translate('If you want to know how to use this module. Push the button below and discover the possibilities of WasabiLib.')) ?></p>

                <p><a
                      href=application/pages/components><?php echo $this->translate('Explore WasabiLib Module') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Get the WasabiLib Skeleton Application</h3>
            </div>
            <div class="panel-body same-height">
                <small>(recommended)</small>
                <?= $this->translate("The WasabiLib ZF2 Skeleton Application comes with a pre-configured layout.phtml. It also comes with
                a composer install routine to put all assets into the right place.") ?>
                <p><a
                                   href="https://github.com/wasabilib/wasabilib_zf2_skeleton_application"><?php echo $this->translate('WasabiLib Skeleton Download') ?> &raquo;</a>
                </p>
            </div>
        </div>
    </div>

    <!--    <div class="col-md-4">-->
    <!--        <div class="panel panel-default">-->
    <!--            <div class="panel-heading">-->
    <!--                <h3 class="panel-title">--><?php //echo $this->translate('Help &amp; Support') ?><!--</h3>-->
    <!--            </div>-->
    <!--            <div class="panel-body">-->
    <!--                <p>-->
    <?php //echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?><!--</p>-->
    <!--                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank">-->
    <?php //echo $this->translate('Ping us on IRC') ?><!-- &raquo;</a></p>-->
    <!--            </div>-->
    <!--        </div>-->
    <!--    </div>-->
        <div class="container">
            <h1>Basic Example & Tryout</h1>

                <div class="highlight" style="min-height: 40px">
                    <div id="start_example_target_id" class="container-fluid"></div>
                </div>

                <button id="inner_html_btn" class="ajax_element" data-href="application/pages/startExample">InnerHtml Example</button><br><br>
            </div>
            <div class="highlight">
        <pre>
              <p>
                  //inside the phtml<br>
                  &lt;div id=&quot;start_example_target_id&quot;&gt;&lt;/div&gt;
              </p>
            <code class="language-php">
//on the server
public function startExampleAction(){
   $innerHtml = new InnerHtml("#start_example_target_id","This comes right from the Server");
   return $this->getResponse()->setContent(new Response($innerHtml));
}
            </code>
        </pre>
            </div>
        </div>
</div>


