<?= $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Wasabi '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- CSS -->
        <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/vendor/wasabi/css/wasabi.gritter.css')
            ->prependStylesheet($this->basePath() . '/vendor/wasabi/css/wasabi.modal.css')
            ->prependStylesheet($this->basePath() . '/vendor/wasabi/css/wasabi.suggest.css')
            ->prependStylesheet($this->basePath() . '/vendor/wasabi/css/wasabi.wizard.css')
            ->prependStylesheet($this->basePath() . '/vendor/bootstrap/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/vendor/bootstrap/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/vendor/fontAwesome/css/font-awesome.min.css')
            ; ?>

        <!-- JAVASCRIPT's -->
        <?= $this->headScript()
            ->prependFile($this->basePath() . '/vendor/wasabi/js/wasabilib.min.js')
            ->prependFile($this->basePath() . '/vendor/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/vendor/wasabi/js/wasabi.gritter.js')
            ->prependFile($this->basePath() . '/vendor/wasabi/js/wasabi.suggest.js')
            ->prependFile($this->basePath() . '/vendor/jquery/js/jquery-2.1.4.min.js')
            ->prependFile($this->basePath() . '/vendor/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/vendor/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav id="wasabilib" class="navbar navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>

                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>"><img class="pull-left" src="<?= $this->basePath('img/skeletonLogo.png') ?>" alt="WasabiLib.org">&nbsp;<?= $this->translate('Wasabi Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?= $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav')->setPartial('layout/navigation.phtml'); ?>

                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?= $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> WasabiLib.org <?= $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?= $this->inlineScript() ?>
    </body>
</html>
