<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('WasabiLib - A powerful ajax module for ZF2') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
//            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/dropzone.basic.css') //dropzone
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/wasabi.gritter.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/wasabi.modal.standard.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/wasabi.modal.dialog.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/wasabi.modal.info.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/font-awesome.min.css')
            ->prependStylesheet($this->basePath() . '/css/docs.min.css')
            ;
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
//            ->prependFile($this->basePath() . '/wasabilib_assets/js/dropzone.min.js')
            ->prependFile($this->basePath() . '/wasabilib_assets/js/WasabiLib/Communication.js')
            ->prependFile($this->basePath() . '/wasabilib_assets/js/WasabiLib/Recipients/gritter.js')
            ->prependFile($this->basePath() . '/wasabilib_assets/js/WasabiLib/Recipients/common.js')
            ->prependFile($this->basePath() . '/wasabilib_assets/js/WasabiLib/Recipients/config.js')
            ->prependFile($this->basePath() . '/wasabilib_assets/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/wasabilib_assets/js/WasabiLib/wasabi.gritter.js')
            ->prependFile($this->basePath() . '/wasabilib_assets/js/jquery-min.js')
            ->prependFile($this->basePath() . '/wasabilib_assets/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/wasabilib_assets/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <nav id="wasabilib" class="navbar navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                   <img class="wasabi_logo" src="<?php echo $this->basePath('img/skeletonLogo.png') ?>" alt="Wasabi"/>
                    <?php echo $this->translate('WasabiLib DevPortal') ?>
                </a>
            </div>
            <div class="collapse navbar-collapse">
                <?php // <-- Add this !!
                echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav');

                ?>
                <form style="padding-top: 12px" class="pull-right"action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                    <input type="hidden" name="cmd" value="_s-xclick">
                    <input type="hidden" name="hosted_button_id" value="SPMY86W5R4B7S">
                    <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                    <img alt="" border="0" src="https://www.paypalobjects.com/de_DE/i/scr/pixel.gif" width="1" height="1">
                </form>

            </div><!--/.nav-collapse -->
        </div>
    </nav>

        <div class="container" style="margin-top:70px">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>Code licensed under the
                    <a href="https://github.com/angular/angular.js/blob/master/LICENSE" target="_blank">The
                        MIT License</a>. Documentation licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.
                    <br>WasabiLib is developed by Nico Berndt, Norman Albusberger and Sascha Qualitz
                </p>
                <p>&copy; <?php echo date('Y') ?> WasabiLib.org <?php echo $this->translate('All rights reserved.') ?>
                <div class="fb-share-button" data-href="http://www.wasabilib.org" data-layout="button"></div>
    </p>

            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
