<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
//            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/dropzone.basic.css') //dropzone
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/wasabi.gritter.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/wasabi.modal.standard.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/wasabi.modal.dialog.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/wasabi.modal.info.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/wasabilib_assets/css/font-awesome.min.css')
            ->prependStylesheet($this->basePath() . '/css/docs.min.css')
            ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/wasabilib_assets/js/WasabiLib/wasabilib.min.js')
            ->prependFile($this->basePath() . '/wasabilib_assets/js/WasabiLib/ext_lib/bootstrap.min.js')
            ->prependFile($this->basePath() . '/wasabilib_assets/js/WasabiLib/ext_lib/wasabi.gritter.js')
            ->prependFile($this->basePath() . '/wasabilib_assets/js/WasabiLib/ext_lib/wasabi.suggest.js')
            ->prependFile($this->basePath() . '/wasabilib_assets/js/WasabiLib/ext_lib/jquery-min.js')
            ->prependFile($this->basePath() . '/wasabilib_assets/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/wasabilib_assets/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav id="wasabilib" class="navbar navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/skeletonLogo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Wasabi Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php // <-- Add this !!
                    echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav');

                    ?>

                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> WasabiLib.org <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
